- name: Restart iscsi initiator
  ansible.builtin.service:
    name: iscsid
    state: restarted

- name: Restart mpath service
  ansible.builtin.service: 
    name: multipathd
    state: restarted

# - name: Create multipath init configuration
#   shell: "/sbin/mpathconf --enable"

- name: Save targetcli configuration
  shell: "yes|targetcli saveconfig"