---
- name: General setup
  hosts: all
  become: true
  # pre_tasks:
  #   - debug: 
  #       msg: "{{ hostvars[ item ].ansible_host }}"
  #     loop: "{{ groups['nginx_wp']}}"

  tasks:
    - name: Set hostname and /etc/hosts
      block:
        - name: Set static hostname
          ansible.builtin.hostname:
            name: "{{ inventory_hostname_short }}"

        # - name: Add FQDN to /etc/hosts
        #   ansible.builtin.lineinfile:
        #     dest: /etc/hosts
        #     regexp: '^127\.0\.1\.1'
        #     line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }}"
        
        - name: Add IP address of all hosts to all hosts
          ansible.builtin.lineinfile:
            dest: /etc/hosts
            regexp: '.*{{ item }}$'
            line: "{{ hostvars[item].ansible_facts.default_ipv4.address }} {{item}}"
            state: present
          #when: item != ansible_hostname
          loop: "{{ groups.all }}"

- name: Setup MariaDB
  hosts: db
  become: true
  roles:
    - db
  
- name: Setup backend servers with WordPress
  hosts: nginx_wp
  become: true
  tags: backend
  roles:
    - wordpress

- name: Setup NGINX reverse-proxy
  hosts: nginx_lb
  become: true
  tags: frontend
  roles:
    - nginx-rp
  
  post_tasks:
    - name: Check validity of nginx.conf
      ansible.builtin.command: angie -t
      register: nginx_checkconf
      changed_when: False
