---
- name: Create database for WordPress
  community.mysql.mysql_db:
    name: "{{ wp_db }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
    state: present
    # host: localhost
    # login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create DB user for WordPress
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_pass }}"
    priv: "{{ wp_db }}.*:ALL"
    #host_all: true
    state: present
    host: "{{ item }}" #localhost
    # login_unix_socket: /var/lib/mysql/mysql.sock
  loop: "{{ groups['backend'] + groups['db_lb']}}"

# - name: Enable DB user for WordPress
#   community.mysql.mysql_user:
#     name: "{{ wp_db_user }}"
#     priv: "{{ wp_db }}.*:ALL"
#     #host_all: true
#     state: present
#     host: "{{ item }}"
#     # login_unix_socket: /var/lib/mysql/mysql.sock
#   loop: "{{ groups['backend'] }}"

- name: Create DB user for HAProxy check
  community.mysql.mysql_user:
    name: haproxy_check
    # password: clustercheckpassword!
    #priv: "*.*:PROCESS"
    plugin: mysql_native_password
    #host_all: true
    state: present
    host: haproxy
    # login_unix_socket: /var/lib/mysql/mysql.sock
